version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - client/.env
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
