version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro 
    depends_on:
      - backend
      - frontend
