version: "3.8"

services:
  mongo:
    image: mongo
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    stdin_open: true
    tty: true
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
